### ISSUE TITLE
Fails to build on Debian 10.3

### ISSUE THREAD

**Issue by ranma** [8051Enthusiast/at51#3] opened 2020-04-15 19:11 UTC
ii  cargo          0.35.0-2     amd64        Rust package manager
ii  rustc                                         1.34.2+dfsg1-1                               amd64        Rust systems programming language

$ cargo build
   Updating crates.io index
  Downloaded clap v2.33.0
  Downloaded bitflags v1.2.1
  Downloaded rustfft v3.0.1
  Downloaded serde_json v1.0.48
  Downloaded dirs v2.0.2
  Downloaded nom v5.1.1
  Downloaded num-traits v0.2.11
  Downloaded lazy_static v1.4.0
  Downloaded serde v1.0.104
  Downloaded itoa v0.4.5
  Downloaded version_check v0.9.1
  Downloaded atty v0.2.14
  Downloaded memchr v2.3.3
  Downloaded strength_reduce v0.2.3
  Downloaded num-integer v0.1.42
  Downloaded unicode-width v0.1.7
  Downloaded ryu v1.0.3
  Downloaded ansi_term v0.11.0
  Downloaded dirs-sys v0.3.4
  Downloaded transpose v0.1.0
  Downloaded textwrap v0.11.0
  Downloaded strsim v0.8.0
  Downloaded vec_map v0.8.1
  Downloaded num-complex v0.2.4
  Downloaded ar v0.8.0
  Downloaded libc v0.2.67
  Downloaded autocfg v1.0.0
  Downloaded serde_derive v1.0.104
  Downloaded quote v1.0.3
  Downloaded cfg-if v0.1.9
  Downloaded syn v1.0.16
  Downloaded proc-macro2 v1.0.9
  Downloaded lexical-core v0.6.7
  Downloaded rustc_version v0.2.3
  Downloaded arrayvec v0.4.12
  Downloaded unicode-xid v0.2.0
  Downloaded semver v0.9.0
  Downloaded semver-parser v0.7.0
  Downloaded nodrop v0.1.14
  Downloaded static_assertions v0.3.4
   Compiling proc-macro2 v1.0.9
   Compiling unicode-xid v0.2.0
   Compiling semver-parser v0.7.0
   Compiling autocfg v1.0.0
   Compiling syn v1.0.16
   Compiling ryu v1.0.3
   Compiling libc v0.2.67
   Compiling arrayvec v0.4.12
   Compiling bitflags v1.2.1
   Compiling version_check v0.9.1
   Compiling memchr v2.3.3
   Compiling serde v1.0.104
   Compiling nodrop v0.1.14
   Compiling static_assertions v0.3.4
   Compiling cfg-if v0.1.9
   Compiling unicode-width v0.1.7
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
   Compiling vec_map v0.8.1
   Compiling itoa v0.4.5
   Compiling strength_reduce v0.2.3
   Compiling transpose v0.1.0
   Compiling ar v0.8.0
   Compiling lazy_static v1.4.0
   Compiling semver v0.9.0
   Compiling nom v5.1.1
   Compiling num-traits v0.2.11
   Compiling num-complex v0.2.4
   Compiling num-integer v0.1.42
   Compiling textwrap v0.11.0
   Compiling rustc_version v0.2.3
   Compiling lexical-core v0.6.7
   Compiling dirs-sys v0.3.4
   Compiling atty v0.2.14
   Compiling clap v2.33.0
   Compiling quote v1.0.3
   Compiling dirs v2.0.2
   Compiling rustfft v3.0.1
   Compiling serde_derive v1.0.104
   Compiling serde_json v1.0.48
   Compiling at51 v0.4.0 (/ssdhome/ranma/src/at51)
error[E0277]: the trait bound `std::iter::Take<std::slice::Iter<'_, num_complex::Complex<f32>>>: std::iter::DoubleEndedIterator` is not satisfied
  --> src/base.rs:93:18
   |
93 |                 .rev()
   |                  ^^^ the trait `std::iter::DoubleEndedIterator` is not implemented for `std::iter::Take<std::slice::Iter<'_, num_complex::Complex<f32>>>`

error[E0599]: no method named `cycle` found for type `std::iter::Rev<std::iter::Take<std::slice::Iter<'_, num_complex::Complex<f32>>>>` in the current scope
  --> src/base.rs:94:18
   |
94 |                 .cycle()
   |                  ^^^^^
   |
   = note: the method `cycle` exists but the following trait bounds were not satisfied:
           `&mut std::iter::Rev<std::iter::Take<std::slice::Iter<'_, num_complex::Complex<f32>>>> : std::iter::Iterator`
           `std::iter::Rev<std::iter::Take<std::slice::Iter<'_, num_complex::Complex<f32>>>> : std::iter::Iterator`

error[E0277]: the trait bound `std::string::String: std::convert::From<&std::string::String>` is not satisfied
   --> src/libfind/mod.rs:116:23
    |
116 |                 name: String::from(s),
    |                       ^^^^^^^^^^^^ the trait `std::convert::From<&std::string::String>` is not implemented for `std::string::String`
    |
    = help: the following implementations were found:
              <std::string::String as std::convert::From<&'a str>>
              <std::string::String as std::convert::From<std::borrow::Cow<'a, str>>>
              <std::string::String as std::convert::From<std::boxed::Box<str>>>
    = note: required by `std::convert::From::from`

error: aborting due to 3 previous errors

Some errors occurred: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `at51`.

**Comment by 8051Enthusiast** [comment] 2020-04-15 19:53
This was caused by some new library features, which aren't available in your version yet.
Should be fixed in the dev-0.4.1 branch (#4). Can you test if it builds?

**Comment by ranma** [comment] 2020-04-15 21:26
It does, thanks for the quick response!
$ git pull
[...]
$ git checkout dev-0.4.1  
[...]
$ cargo build
  Downloaded serde v1.0.106
  Downloaded libc v0.2.69
  Downloaded serde_derive v1.0.106
  Downloaded proc-macro2 v1.0.10
  Downloaded syn v1.0.17
  Downloaded serde_json v1.0.51
   Compiling proc-macro2 v1.0.10
   Compiling syn v1.0.17
   Compiling libc v0.2.69
   Compiling serde v1.0.106
   Compiling dirs-sys v0.3.4
   Compiling atty v0.2.14
   Compiling quote v1.0.3
   Compiling clap v2.33.0
   Compiling dirs v2.0.2
   Compiling serde_derive v1.0.106
   Compiling serde_json v1.0.51
   Compiling at51 v0.4.1 (/ssdhome/ranma/src/at51)
    Finished dev [unoptimized + debuginfo] target(s) in 30.02s

**Closed as completed** 2020-04-15 21:46 UTC
Labels: bug
